import type { BrandRegistryItem } from "./brandSchema";

export const brandLogoBasePath = "/brand-logos";

export const brands = [
  {
    id: "openai",
    name: "OpenAI",
    aliases: ["openai", "chatgpt", "gpt"],
    category: "ai",
    logoPath: `${brandLogoBasePath}/openai.svg`,
    logoVariant: "mono",
    accentColor: "#10A37F",
    cardGradient: ["#063B32", "#07111F"],
    trademarkOwner: "OpenAI",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "claude",
    name: "Claude",
    aliases: ["claude", "anthropic", "claude code"],
    category: "ai",
    logoPath: `${brandLogoBasePath}/claude.svg`,
    logoVariant: "full_color",
    accentColor: "#D97745",
    cardGradient: ["#3A2012", "#07111F"],
    trademarkOwner: "Anthropic",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "google",
    name: "Google",
    aliases: ["google", "google workspace", "gmail", "drive", "docs", "sheets"],
    category: "productivity",
    logoPath: `${brandLogoBasePath}/google.svg`,
    logoVariant: "full_color",
    accentColor: "#34A853",
    cardGradient: ["#0F3D22", "#07111F"],
    trademarkOwner: "Google LLC",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "aws",
    name: "AWS",
    aliases: ["aws", "amazon web services", "amazon cloud"],
    category: "cloud",
    logoPath: `${brandLogoBasePath}/aws.svg`,
    logoVariant: "full_color",
    accentColor: "#FF9900",
    cardGradient: ["#3B2709", "#07111F"],
    trademarkOwner: "Amazon Web Services, Inc.",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "jellyfin",
    name: "Jellyfin",
    aliases: ["jellyfin", "media server", "jellyfin media"],
    category: "self_hosted",
    logoPath: `${brandLogoBasePath}/jellyfin.svg`,
    logoVariant: "full_color",
    accentColor: "#AA5CC3",
    cardGradient: ["#26143A", "#07111F"],
    trademarkOwner: "Jellyfin Project",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "docker",
    name: "Docker",
    aliases: ["docker", "containers", "container"],
    category: "devtools",
    logoPath: `${brandLogoBasePath}/docker.svg`,
    logoVariant: "full_color",
    accentColor: "#2496ED",
    cardGradient: ["#063052", "#07111F"],
    trademarkOwner: "Docker, Inc.",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "unifi",
    name: "UniFi",
    aliases: ["unifi", "ubiquiti", "ui network", "network controller"],
    category: "networking",
    logoPath: `${brandLogoBasePath}/unifi.svg`,
    logoVariant: "mono",
    accentColor: "#00A0DF",
    cardGradient: ["#053047", "#07111F"],
    trademarkOwner: "Ubiquiti Inc.",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "vscode",
    name: "VS Code",
    aliases: ["vscode", "vs code", "visual studio code", "code editor"],
    category: "devtools",
    logoPath: `${brandLogoBasePath}/vscode.svg`,
    logoVariant: "full_color",
    accentColor: "#007ACC",
    cardGradient: ["#052D4D", "#07111F"],
    trademarkOwner: "Microsoft Corporation",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "github",
    name: "GitHub",
    aliases: ["github", "git hub", "pull request", "workflow"],
    category: "devtools",
    logoPath: `${brandLogoBasePath}/github.svg`,
    logoVariant: "mono",
    accentColor: "#FFFFFF",
    cardGradient: ["#2A213A", "#07111F"],
    trademarkOwner: "GitHub, Inc.",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "homeassistant",
    name: "Home Assistant",
    aliases: ["home assistant", "homeassistant", "home automation", "hass"],
    category: "home_automation",
    logoPath: `${brandLogoBasePath}/homeassistant.svg`,
    logoVariant: "full_color",
    accentColor: "#41BDF5",
    cardGradient: ["#07405B", "#07111F"],
    trademarkOwner: "Open Home Foundation",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "tailscale",
    name: "Tailscale",
    aliases: ["tailscale", "tail scale", "vpn", "wireguard"],
    category: "networking",
    logoPath: `${brandLogoBasePath}/tailscale.svg`,
    logoVariant: "mono",
    accentColor: "#9CA3AF",
    cardGradient: ["#1F2937", "#07111F"],
    trademarkOwner: "Tailscale Inc.",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  },
  {
    id: "obsidian",
    name: "Obsidian",
    aliases: ["obsidian", "obsidian vault", "markdown vault", "local notes"],
    category: "productivity",
    logoPath: `${brandLogoBasePath}/obsidian.svg`,
    logoVariant: "mono",
    accentColor: "#7C3AED",
    cardGradient: ["#27164A", "#07111F"],
    trademarkOwner: "Dynalist Inc.",
    usageNote: "identifier_only",
    allowRecolor: false,
    preferredLogoBackground: "dark"
  }
] satisfies BrandRegistryItem[];

export const brandsById = new Map(brands.map((brand) => [brand.id, brand]));
